services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.settings
