services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: gunicorn backend.backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true

  - type: web
    name: vue-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
